services:
  cmdbesp:
    build: .
    image: mokmail/cmdbesp:latest
    container_name: cmdbesp
    ports:
      - "4455:4455"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  uploads: